CREATE SEQUENCE SEQ_PRODUTOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE PRODUTOS (
    IDPK INTEGER DEFAULT SEQ_PRODUTOS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(500),
    URL_FOTO VARCHAR2(500)
);